[package]
name = "idl_builder"
version = "0.1.3"
edition = "2021"
description = "Builder for IDL language for rust."
repository = "https://github.com/adrianos42/idl_builder"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.78"
